// Test output.
import void testPrint(const ubyte * str, ...) noexcept;

exception TestError();

void f() {
	scope(success) {
		throw TestError();
	}
}

// Entry point.
export int testEntryPoint(unused int argc, unused ubyte ** argv) {
	try {
		testPrint(C"testEntryPoint: Before f().");
		f();
		testPrint(C"testEntryPoint: After f().");
		return 1;
	} catch (TestError e) {
		testPrint(C"testEntryPoint: Caught exception.");
		return 0;
	}
}

