exception TestError();

class TestClass() {
	bool __isvalid() const {
		throw TestError();
	}
}
